name: autotrigger

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        name: checkout repository
 
      - uses: kaali09/canary-action@v1
        name: run a custom script
        with:
          kubeconfig: ${{ secrets.KUBECONFIG }}
          namespace: confluent
          args: ""
