
   
name: Create and Publish Docker Image

on:
  workflow_call:
    inputs:
      image_name:
        required: false
        type: string
      tag: 
        type: string
    secrets:
      registry_username:
        required: false
      registry_password:
        required: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:      
      - uses: actions/checkout@v2
      
      - name: Setup BuildX
        uses: docker/setup-buildx-action@v1

      - name: Set the tag
        run: |
          if [ -z "${{inputs.tag}}" ]
          then
            echo "final_tag=latest" >> $GITHUB_ENV
          else
            echo "final_tag=${{inputs.tag}}" >> $GITHUB_ENV
          fi
          
  do-something-else:
    runs-on: ubuntu-latest

    steps:
    - run: echo "Hello"
